context("infiniter functions")
test_that("Test generateFakeClusters",{
  expect_equal(length(generateFakeClusters()), 3)
  expect_equal(names(generateFakeClusters()), c('points','centers','ids'))
  tmp<-generateFakeClusters(nDim=3,nPoints=40,nCluster=4)
  expect_equal(dim(tmp[['points']]), c(4*40,3))
  expect_equal(dim(tmp[['centers']]), c(4,3))
  expect_equal(length(tmp[['ids']]), 4*40)
  expect_equal(unique(table(tmp[['ids']])), 40)
  tmp<-generateFakeClusters(nDim=4,nPoints=30,nCluster=5,withinSd=0,betweenSd=0)
  expect_equal(unique(as.vector(tmp[['points']])), 0)
  expect_equal(unique(as.vector(tmp[['centers']])), 0)
})
